import "./globals.css";
import { BsFillMoonStarsFill } from "react-icons/bs";

export const metadata = {
  title: "Patrick Rooney Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <section className="bg-green-400 min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1>Patrick Rooney</h1>
          <ul>
            <li>
              <BsFillMoonStarsFill />
            </li>
            <li>
              <a href="#">Resume</a>
            </li>
          </ul>
        </nav>
      </section> */}
      <body >{children}</body>
    </html>
  );
}
